name: SSH into our runners

on:
  push:
    branches:
      - ping_author_2

jobs:
  ssh_runner:
    name: "SSH"
    runs-on: ubuntu-22.04
    env:
      github_actor: ydshieh
    steps:
      - name: Store Slack infos
        shell: bash
        run: |
          echo "${{ env.github_actor }}"
          echo $SLACKCHANNEL

          for word in I love dogs "${{ env.github_actor }}"
          do
            echo $word
            echo "$word"_SLACK_ID
            echo ${{ secrets[format('{0}', '"$word"_SLACK_ID')] }}
            if [ "${{ secrets['$word_SLACK_ID'] }}" != "" ]; then
              export SLACKCHANNEL="$SLACKCHANNEL",$word:hello-${{ secrets[format('{0}_{1}', env.word, 'SLACK_ID')] }}
            else
              export SLACKCHANNEL="$SLACKCHANNEL",$word:null
            fi
          done

          export SLACKCHANNEL="${SLACKCHANNEL:1}"
          echo $SLACKCHANNEL

#      - name: Store Slack infos
#        shell: bash
#        run: |
#          echo ${{ env.SLACKCHANNEL }}
#          python -c 'import os; o = os.environ["SLACKCHANNEL"][:8]; print(o)'