name: SSH into our runners

on:
  push:
    branches:
      - ping_author_2

jobs:
  ssh_runner:
    name: "SSH"
    runs-on: ubuntu-22.04
    env:
      github_actor: ydshieh
    steps:
      - name: Store Slack infos
        shell: bash
        run: |
          echo "${{ env.github_actor }}"
          if [ "${{ secrets[format('{0}_{1}', env.github_actor, 'SLACK_ID')] }}" != "" ]; then
            echo "SLACKCHANNEL=hello-${{ secrets[format('{0}_{1}', env.github_actor, 'SLACK_ID')] }}" >> $GITHUB_ENV
          else
            echo "SLACKCHANNEL=hello-${{ secrets.SLACK_CIFEEDBACK_CHANNEL }}" >> $GITHUB_ENV
          fi
