name: SSH into our runners

on:
  push:
    branches:
      - ping_author_2

jobs:
  ssh_runner:
    name: "SSH"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        author: [ydshieh]
    steps:
      - name: Store Slack infos
        shell: bash
        run: |
          echo "${{ matrix.author }}"
          echo $SLACKCHANNEL

          if [ "${{ secrets[format('{0}_{1}', matrix.author, 'SLACK_ID')] }}" != "" ]; then
            export SLACKCHANNEL="$SLACKCHANNEL",$word:hello-${{ secrets[format('{0}_{1}', matrix.author, 'SLACK_ID')] }}
          else
            export SLACKCHANNEL="$SLACKCHANNEL",$word:null
          fi

          export SLACKCHANNEL="${SLACKCHANNEL:1}"
          echo $SLACKCHANNEL

#      - name: Store Slack infos
#        shell: bash
#        run: |
#          echo ${{ env.SLACKCHANNEL }}
#          python -c 'import os; o = os.environ["SLACKCHANNEL"][:8]; print(o)'